/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import { GraphQLSchema, GraphQLObjectType, GraphQLNonNull, GraphQLString } from "graphql";
import { ping as queryPingResolver } from "./../src/schema/ping";
export function getSchema(): GraphQLSchema {
    const PongType: GraphQLObjectType = new GraphQLObjectType({
        name: "Pong",
        description: "An object representing a test response from the GraphQL server",
        fields() {
            return {
                pong: {
                    description: "Set whenever the GraphQL server is working properly",
                    name: "pong",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                ping: {
                    description: "Call this to check that the GraphQL server is working properly",
                    name: "ping",
                    type: new GraphQLNonNull(PongType),
                    resolve() {
                        return queryPingResolver();
                    }
                }
            };
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        types: [PongType, QueryType]
    });
}
