/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Boolean': unknown;
    'Date': unknown;
    'DateTime': unknown;
    'Float': unknown;
    'ID': unknown;
    'Int': unknown;
    'Money': { kind: 'OBJECT'; name: 'Money'; fields: { 'amount': { name: 'amount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'currency': { name: 'currency'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'MoneyInput': { kind: 'INPUT_OBJECT'; name: 'MoneyInput'; isOneOf: false; inputFields: [{ name: 'amount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; }; defaultValue: null }, { name: 'currency'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'netWorthCategoryCreate': { name: 'netWorthCategoryCreate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INTERFACE'; name: 'NetWorthCategory'; ofType: null; }; } }; 'netWorthCategoryDelete': { name: 'netWorthCategoryDelete'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Void'; ofType: null; }; } }; 'netWorthCategoryUpdate': { name: 'netWorthCategoryUpdate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INTERFACE'; name: 'NetWorthCategory'; ofType: null; }; } }; 'netWorthCreate': { name: 'netWorthCreate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NetWorthEntry'; ofType: null; }; } }; 'netWorthDelete': { name: 'netWorthDelete'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Void'; ofType: null; }; } }; 'netWorthUpdate': { name: 'netWorthUpdate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NetWorthEntry'; ofType: null; }; } }; }; };
    'NetWorthAssetType': { name: 'NetWorthAssetType'; enumValues: 'CASH' | 'MISC' | 'OPTION' | 'PENSION' | 'PROPERTY' | 'STOCK'; };
    'NetWorthCategory': { kind: 'INTERFACE'; name: 'NetWorthCategory'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; possibleTypes: 'NetWorthCategoryAsset' | 'NetWorthCategoryLiability' | 'NetWorthCategoryOption'; };
    'NetWorthCategoryAsset': { kind: 'OBJECT'; name: 'NetWorthCategoryAsset'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'type': { name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'NetWorthAssetType'; ofType: null; }; } }; }; };
    'NetWorthCategoryAssetInput': { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryAssetInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'NetWorthAssetType'; ofType: null; }; }; defaultValue: null }]; };
    'NetWorthCategoryAssetPatch': { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryAssetPatch'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'type'; type: { kind: 'ENUM'; name: 'NetWorthAssetType'; ofType: null; }; defaultValue: null }]; };
    'NetWorthCategoryConnection': { kind: 'OBJECT'; name: 'NetWorthCategoryConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NetWorthCategoryEdge'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'NetWorthCategoryEdge': { kind: 'OBJECT'; name: 'NetWorthCategoryEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INTERFACE'; name: 'NetWorthCategory'; ofType: null; }; } }; }; };
    'NetWorthCategoryInput': { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryInput'; isOneOf: true; inputFields: [{ name: 'asset'; type: { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryAssetInput'; ofType: null; }; defaultValue: null }, { name: 'liability'; type: { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryLiabilityInput'; ofType: null; }; defaultValue: null }, { name: 'option'; type: { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryOptionInput'; ofType: null; }; defaultValue: null }]; };
    'NetWorthCategoryLiability': { kind: 'OBJECT'; name: 'NetWorthCategoryLiability'; fields: { 'asset': { name: 'asset'; type: { kind: 'OBJECT'; name: 'NetWorthCategoryAsset'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'interestRate': { name: 'interestRate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'type': { name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'NetWorthLiabilityType'; ofType: null; }; } }; }; };
    'NetWorthCategoryLiabilityInput': { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryLiabilityInput'; isOneOf: false; inputFields: [{ name: 'assetId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'interestRate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'type'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'NetWorthLiabilityType'; ofType: null; }; }; defaultValue: null }]; };
    'NetWorthCategoryLiabilityPatch': { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryLiabilityPatch'; isOneOf: false; inputFields: [{ name: 'assetId'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'interestRate'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'type'; type: { kind: 'ENUM'; name: 'NetWorthLiabilityType'; ofType: null; }; defaultValue: null }]; };
    'NetWorthCategoryOption': { kind: 'OBJECT'; name: 'NetWorthCategoryOption'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'NetWorthCategoryOptionInput': { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryOptionInput'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'NetWorthCategoryOptionPatch': { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryOptionPatch'; isOneOf: false; inputFields: [{ name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'NetWorthCategoryPatch': { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryPatch'; isOneOf: true; inputFields: [{ name: 'asset'; type: { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryAssetPatch'; ofType: null; }; defaultValue: null }, { name: 'liability'; type: { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryLiabilityPatch'; ofType: null; }; defaultValue: null }, { name: 'option'; type: { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryOptionPatch'; ofType: null; }; defaultValue: null }]; };
    'NetWorthCategoryRef': { kind: 'INPUT_OBJECT'; name: 'NetWorthCategoryRef'; isOneOf: true; inputFields: [{ name: 'asset'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'liability'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'option'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }]; };
    'NetWorthCurrencyRate': { kind: 'OBJECT'; name: 'NetWorthCurrencyRate'; fields: { 'base': { name: 'base'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'currency': { name: 'currency'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'rate': { name: 'rate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; }; };
    'NetWorthCurrencyRateInput': { kind: 'INPUT_OBJECT'; name: 'NetWorthCurrencyRateInput'; isOneOf: false; inputFields: [{ name: 'base'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'currency'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'rate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; }; defaultValue: null }]; };
    'NetWorthEntry': { kind: 'OBJECT'; name: 'NetWorthEntry'; fields: { 'currencyRates': { name: 'currencyRates'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NetWorthCurrencyRate'; ofType: null; }; }; }; } }; 'date': { name: 'date'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Date'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'values': { name: 'values'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NetWorthValue'; ofType: null; }; }; }; } }; }; };
    'NetWorthEntryConnection': { kind: 'OBJECT'; name: 'NetWorthEntryConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NetWorthEntryEdge'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'NetWorthEntryEdge': { kind: 'OBJECT'; name: 'NetWorthEntryEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NetWorthEntry'; ofType: null; }; } }; }; };
    'NetWorthLiabilityType': { name: 'NetWorthLiabilityType'; enumValues: 'CREDIT_CARD' | 'LOAN' | 'MISC'; };
    'NetWorthValue': { kind: 'OBJECT'; name: 'NetWorthValue'; fields: { 'amounts': { name: 'amounts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Money'; ofType: null; }; }; }; } }; 'asset': { name: 'asset'; type: { kind: 'OBJECT'; name: 'NetWorthCategoryAsset'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'liability': { name: 'liability'; type: { kind: 'OBJECT'; name: 'NetWorthCategoryLiability'; ofType: null; } }; 'option': { name: 'option'; type: { kind: 'OBJECT'; name: 'NetWorthCategoryOption'; ofType: null; } }; }; };
    'NetWorthValueAssetInput': { kind: 'INPUT_OBJECT'; name: 'NetWorthValueAssetInput'; isOneOf: false; inputFields: [{ name: 'amounts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'MoneyInput'; ofType: null; }; }; }; }; defaultValue: null }, { name: 'categoryId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }]; };
    'NetWorthValueInput': { kind: 'INPUT_OBJECT'; name: 'NetWorthValueInput'; isOneOf: true; inputFields: [{ name: 'asset'; type: { kind: 'INPUT_OBJECT'; name: 'NetWorthValueAssetInput'; ofType: null; }; defaultValue: null }, { name: 'liability'; type: { kind: 'INPUT_OBJECT'; name: 'NetWorthValueLiabilityInput'; ofType: null; }; defaultValue: null }, { name: 'option'; type: { kind: 'INPUT_OBJECT'; name: 'NetWorthValueOptionInput'; ofType: null; }; defaultValue: null }]; };
    'NetWorthValueLiabilityInput': { kind: 'INPUT_OBJECT'; name: 'NetWorthValueLiabilityInput'; isOneOf: false; inputFields: [{ name: 'amounts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'MoneyInput'; ofType: null; }; }; }; }; defaultValue: null }, { name: 'categoryId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }]; };
    'NetWorthValueOptionInput': { kind: 'INPUT_OBJECT'; name: 'NetWorthValueOptionInput'; isOneOf: false; inputFields: [{ name: 'amounts'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'MoneyInput'; ofType: null; }; }; }; }; defaultValue: null }, { name: 'categoryId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }]; };
    'PageInfo': { kind: 'OBJECT'; name: 'PageInfo'; fields: { 'endCursor': { name: 'endCursor'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'hasNextPage': { name: 'hasNextPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'hasPreviousPage': { name: 'hasPreviousPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'startCursor': { name: 'startCursor'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; }; };
    'Pong': { kind: 'OBJECT'; name: 'Pong'; fields: { 'pong': { name: 'pong'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'netWorth': { name: 'netWorth'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NetWorthEntryConnection'; ofType: null; }; } }; 'netWorthCategories': { name: 'netWorthCategories'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'NetWorthCategoryConnection'; ofType: null; }; } }; 'ping': { name: 'ping'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Pong'; ofType: null; }; } }; }; };
    'String': unknown;
    'Void': { kind: 'OBJECT'; name: 'Void'; fields: { '_': { name: '_'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}