/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import type { GqlScalar } from "grats";
import type { DateTime as DateTimeInternal } from "./../schema/date-time";
import { GraphQLSchema, GraphQLObjectType, GraphQLNonNull, GraphQLString, GraphQLScalarType } from "graphql";
import { ping as queryPingResolver } from "./../schema/ping";
export type SchemaConfig = {
    scalars: {
        DateTime: GqlScalar<DateTimeInternal>;
    };
};
export function getSchema(config: SchemaConfig): GraphQLSchema {
    const PongType: GraphQLObjectType = new GraphQLObjectType({
        name: "Pong",
        description: "An object representing a test response from the GraphQL server",
        fields() {
            return {
                pong: {
                    description: "Set whenever the GraphQL server is working properly",
                    name: "pong",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                ping: {
                    description: "Call this to check that the GraphQL server is working properly",
                    name: "ping",
                    type: new GraphQLNonNull(PongType),
                    resolve() {
                        return queryPingResolver();
                    }
                }
            };
        }
    });
    const DateTimeType: GraphQLScalarType = new GraphQLScalarType({
        description: "ISO-8601 date-time. Serialises as an ISO-8601 string over the wire.",
        name: "DateTime",
        ...config.scalars.DateTime
    });
    return new GraphQLSchema({
        query: QueryType,
        types: [DateTimeType, PongType, QueryType]
    });
}
