/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import type { GqlScalar } from "grats";
import type { Date as DateInternal } from "./../graphql/date";
import type { DateTime as DateTimeInternal } from "./../graphql/date-time";
import { GraphQLSchema, GraphQLObjectType, GraphQLNonNull, GraphQLString, GraphQLScalarType, GraphQLInputObjectType, GraphQLFloat, GraphQLBoolean } from "graphql";
import { ping as queryPingResolver } from "./../graphql/ping";
export type SchemaConfig = {
    scalars: {
        Date: GqlScalar<DateInternal>;
        DateTime: GqlScalar<DateTimeInternal>;
    };
};
export function getSchema(config: SchemaConfig): GraphQLSchema {
    const PongType: GraphQLObjectType = new GraphQLObjectType({
        name: "Pong",
        description: "An object representing a test response from the GraphQL server",
        fields() {
            return {
                pong: {
                    description: "Set whenever the GraphQL server is working properly",
                    name: "pong",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                ping: {
                    description: "Call this to check that the GraphQL server is working properly",
                    name: "ping",
                    type: new GraphQLNonNull(PongType),
                    resolve() {
                        return queryPingResolver();
                    }
                }
            };
        }
    });
    const DateType: GraphQLScalarType = new GraphQLScalarType({
        description: "ISO-8601 calendar date (YYYY-MM-DD). No time-of-day component.",
        name: "Date",
        ...config.scalars.Date
    });
    const DateTimeType: GraphQLScalarType = new GraphQLScalarType({
        description: "ISO-8601 date-time. Serialises as an ISO-8601 string over the wire.",
        name: "DateTime",
        ...config.scalars.DateTime
    });
    const MoneyInputType: GraphQLInputObjectType = new GraphQLInputObjectType({
        description: "Client-supplied monetary value. `amount` is in major units of `currency` (e.g. 123.45 for \u00A3123.45).",
        name: "MoneyInput",
        fields() {
            return {
                amount: {
                    description: "Amount in major units of `currency` (e.g. 123.45 for \u00A3123.45).",
                    name: "amount",
                    type: new GraphQLNonNull(GraphQLFloat)
                },
                currency: {
                    description: "ISO-4217 currency code (e.g. \"GBP\").",
                    name: "currency",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const MoneyType: GraphQLObjectType = new GraphQLObjectType({
        name: "Money",
        description: "A monetary value with an ISO-4217 currency. `amount` is in major units (e.g. 123.45 for \u00A3123.45).",
        fields() {
            return {
                amount: {
                    description: "Amount in major units of `currency` (e.g. 123.45 for \u00A3123.45).",
                    name: "amount",
                    type: new GraphQLNonNull(GraphQLFloat)
                },
                currency: {
                    description: "ISO-4217 currency code (e.g. \"GBP\").",
                    name: "currency",
                    type: new GraphQLNonNull(GraphQLString)
                }
            };
        }
    });
    const VoidType: GraphQLObjectType = new GraphQLObjectType({
        name: "Void",
        description: "Placeholder payload for mutations that have nothing meaningful to return (e.g. delete).\nClients should select `_` (or nothing) and discard the result.",
        fields() {
            return {
                _: {
                    description: "Exists only because GraphQL forbids empty object types. Always null \u2014 ignore it.",
                    name: "_",
                    type: GraphQLBoolean
                }
            };
        }
    });
    return new GraphQLSchema({
        query: QueryType,
        types: [DateType, DateTimeType, MoneyInputType, MoneyType, PongType, QueryType, VoidType]
    });
}
