// Generated by scripts/generate-possible-types.ts. Do not edit.
export const possibleTypes: Record<string, string[]> = {
  InvestmentAsset: ["InvestmentFund", "InvestmentStock"],
  NetWorthCategory: [
    "NetWorthCategoryAsset",
    "NetWorthCategoryLiability",
    "NetWorthCategoryOption",
  ],
  PlanningYearTaxRates: ["PlanningYearTaxRatesUK"],
};
