// Generated by scripts/generate-possible-types.ts. Do not edit.
export const possibleTypes: Record<string, string[]> = {
  "CashContribution": [
    "AssetCashPlanningTransaction",
    "AssetValueSnapshot",
    "InvestmentDeposit"
  ],
  "InvestmentAsset": [
    "InvestmentFund",
    "InvestmentStock"
  ],
  "NetWorthCategory": [
    "NetWorthCategoryAsset",
    "NetWorthCategoryLiability",
    "NetWorthCategoryOption"
  ],
  "NetWorthForecastCategory": [
    "NetWorthForecastFlatAsset",
    "NetWorthForecastFlatLiability",
    "NetWorthForecastGrowthAsset",
    "NetWorthForecastLoan",
    "NetWorthForecastOptionCategory",
    "NetWorthForecastPortfolio"
  ],
  "PlanningYearTaxRates": [
    "PlanningYearTaxRatesUK"
  ]
};
