/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as NetWorthRouteImport } from './../routes/net-worth'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as PlanningIndexRouteImport } from './../routes/planning/index'
import { Route as PlanningYearRouteImport } from './../routes/planning/$year'
import { Route as NetWorthEntriesRouteImport } from './../routes/net-worth/entries'
import { Route as NetWorthCategoriesRouteImport } from './../routes/net-worth/categories'
import { Route as PlanningYearTaxRatesRouteImport } from './../routes/planning/$year/tax-rates'
import { Route as PlanningYearPayslipsRouteImport } from './../routes/planning/$year/payslips'
import { Route as PlanningYearEarningsRouteImport } from './../routes/planning/$year/earnings'
import { Route as PlanningYearBillsRouteImport } from './../routes/planning/$year/bills'
import { Route as PlanningYearAccountsRouteImport } from './../routes/planning/$year/accounts'
import { Route as NetWorthEntriesNewRouteImport } from './../routes/net-worth/entries/new'
import { Route as NetWorthEntriesIdEditRouteImport } from './../routes/net-worth/entries/$id.edit'

const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningIndexRoute = PlanningIndexRouteImport.update({
  id: '/planning/',
  path: '/planning/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningYearRoute = PlanningYearRouteImport.update({
  id: '/planning/$year',
  path: '/planning/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthEntriesRoute = NetWorthEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => NetWorthRoute,
} as any)
const NetWorthCategoriesRoute = NetWorthCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => NetWorthRoute,
} as any)
const PlanningYearTaxRatesRoute = PlanningYearTaxRatesRouteImport.update({
  id: '/tax-rates',
  path: '/tax-rates',
  getParentRoute: () => PlanningYearRoute,
} as any)
const PlanningYearPayslipsRoute = PlanningYearPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => PlanningYearRoute,
} as any)
const PlanningYearEarningsRoute = PlanningYearEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => PlanningYearRoute,
} as any)
const PlanningYearBillsRoute = PlanningYearBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => PlanningYearRoute,
} as any)
const PlanningYearAccountsRoute = PlanningYearAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => PlanningYearRoute,
} as any)
const NetWorthEntriesNewRoute = NetWorthEntriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => NetWorthEntriesRoute,
} as any)
const NetWorthEntriesIdEditRoute = NetWorthEntriesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => NetWorthEntriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/net-worth': typeof NetWorthRouteWithChildren
  '/net-worth/categories': typeof NetWorthCategoriesRoute
  '/net-worth/entries': typeof NetWorthEntriesRouteWithChildren
  '/planning/$year': typeof PlanningYearRouteWithChildren
  '/planning/': typeof PlanningIndexRoute
  '/net-worth/entries/new': typeof NetWorthEntriesNewRoute
  '/planning/$year/accounts': typeof PlanningYearAccountsRoute
  '/planning/$year/bills': typeof PlanningYearBillsRoute
  '/planning/$year/earnings': typeof PlanningYearEarningsRoute
  '/planning/$year/payslips': typeof PlanningYearPayslipsRoute
  '/planning/$year/tax-rates': typeof PlanningYearTaxRatesRoute
  '/net-worth/entries/$id/edit': typeof NetWorthEntriesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/net-worth': typeof NetWorthRouteWithChildren
  '/net-worth/categories': typeof NetWorthCategoriesRoute
  '/net-worth/entries': typeof NetWorthEntriesRouteWithChildren
  '/planning/$year': typeof PlanningYearRouteWithChildren
  '/planning': typeof PlanningIndexRoute
  '/net-worth/entries/new': typeof NetWorthEntriesNewRoute
  '/planning/$year/accounts': typeof PlanningYearAccountsRoute
  '/planning/$year/bills': typeof PlanningYearBillsRoute
  '/planning/$year/earnings': typeof PlanningYearEarningsRoute
  '/planning/$year/payslips': typeof PlanningYearPayslipsRoute
  '/planning/$year/tax-rates': typeof PlanningYearTaxRatesRoute
  '/net-worth/entries/$id/edit': typeof NetWorthEntriesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/net-worth': typeof NetWorthRouteWithChildren
  '/net-worth/categories': typeof NetWorthCategoriesRoute
  '/net-worth/entries': typeof NetWorthEntriesRouteWithChildren
  '/planning/$year': typeof PlanningYearRouteWithChildren
  '/planning/': typeof PlanningIndexRoute
  '/net-worth/entries/new': typeof NetWorthEntriesNewRoute
  '/planning/$year/accounts': typeof PlanningYearAccountsRoute
  '/planning/$year/bills': typeof PlanningYearBillsRoute
  '/planning/$year/earnings': typeof PlanningYearEarningsRoute
  '/planning/$year/payslips': typeof PlanningYearPayslipsRoute
  '/planning/$year/tax-rates': typeof PlanningYearTaxRatesRoute
  '/net-worth/entries/$id/edit': typeof NetWorthEntriesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/net-worth'
    | '/net-worth/categories'
    | '/net-worth/entries'
    | '/planning/$year'
    | '/planning/'
    | '/net-worth/entries/new'
    | '/planning/$year/accounts'
    | '/planning/$year/bills'
    | '/planning/$year/earnings'
    | '/planning/$year/payslips'
    | '/planning/$year/tax-rates'
    | '/net-worth/entries/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/net-worth'
    | '/net-worth/categories'
    | '/net-worth/entries'
    | '/planning/$year'
    | '/planning'
    | '/net-worth/entries/new'
    | '/planning/$year/accounts'
    | '/planning/$year/bills'
    | '/planning/$year/earnings'
    | '/planning/$year/payslips'
    | '/planning/$year/tax-rates'
    | '/net-worth/entries/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/net-worth'
    | '/net-worth/categories'
    | '/net-worth/entries'
    | '/planning/$year'
    | '/planning/'
    | '/net-worth/entries/new'
    | '/planning/$year/accounts'
    | '/planning/$year/bills'
    | '/planning/$year/earnings'
    | '/planning/$year/payslips'
    | '/planning/$year/tax-rates'
    | '/net-worth/entries/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetWorthRoute: typeof NetWorthRouteWithChildren
  PlanningYearRoute: typeof PlanningYearRouteWithChildren
  PlanningIndexRoute: typeof PlanningIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/': {
      id: '/planning/'
      path: '/planning'
      fullPath: '/planning/'
      preLoaderRoute: typeof PlanningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning/$year': {
      id: '/planning/$year'
      path: '/planning/$year'
      fullPath: '/planning/$year'
      preLoaderRoute: typeof PlanningYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth/entries': {
      id: '/net-worth/entries'
      path: '/entries'
      fullPath: '/net-worth/entries'
      preLoaderRoute: typeof NetWorthEntriesRouteImport
      parentRoute: typeof NetWorthRoute
    }
    '/net-worth/categories': {
      id: '/net-worth/categories'
      path: '/categories'
      fullPath: '/net-worth/categories'
      preLoaderRoute: typeof NetWorthCategoriesRouteImport
      parentRoute: typeof NetWorthRoute
    }
    '/planning/$year/tax-rates': {
      id: '/planning/$year/tax-rates'
      path: '/tax-rates'
      fullPath: '/planning/$year/tax-rates'
      preLoaderRoute: typeof PlanningYearTaxRatesRouteImport
      parentRoute: typeof PlanningYearRoute
    }
    '/planning/$year/payslips': {
      id: '/planning/$year/payslips'
      path: '/payslips'
      fullPath: '/planning/$year/payslips'
      preLoaderRoute: typeof PlanningYearPayslipsRouteImport
      parentRoute: typeof PlanningYearRoute
    }
    '/planning/$year/earnings': {
      id: '/planning/$year/earnings'
      path: '/earnings'
      fullPath: '/planning/$year/earnings'
      preLoaderRoute: typeof PlanningYearEarningsRouteImport
      parentRoute: typeof PlanningYearRoute
    }
    '/planning/$year/bills': {
      id: '/planning/$year/bills'
      path: '/bills'
      fullPath: '/planning/$year/bills'
      preLoaderRoute: typeof PlanningYearBillsRouteImport
      parentRoute: typeof PlanningYearRoute
    }
    '/planning/$year/accounts': {
      id: '/planning/$year/accounts'
      path: '/accounts'
      fullPath: '/planning/$year/accounts'
      preLoaderRoute: typeof PlanningYearAccountsRouteImport
      parentRoute: typeof PlanningYearRoute
    }
    '/net-worth/entries/new': {
      id: '/net-worth/entries/new'
      path: '/new'
      fullPath: '/net-worth/entries/new'
      preLoaderRoute: typeof NetWorthEntriesNewRouteImport
      parentRoute: typeof NetWorthEntriesRoute
    }
    '/net-worth/entries/$id/edit': {
      id: '/net-worth/entries/$id/edit'
      path: '/$id/edit'
      fullPath: '/net-worth/entries/$id/edit'
      preLoaderRoute: typeof NetWorthEntriesIdEditRouteImport
      parentRoute: typeof NetWorthEntriesRoute
    }
  }
}

interface NetWorthEntriesRouteChildren {
  NetWorthEntriesNewRoute: typeof NetWorthEntriesNewRoute
  NetWorthEntriesIdEditRoute: typeof NetWorthEntriesIdEditRoute
}

const NetWorthEntriesRouteChildren: NetWorthEntriesRouteChildren = {
  NetWorthEntriesNewRoute: NetWorthEntriesNewRoute,
  NetWorthEntriesIdEditRoute: NetWorthEntriesIdEditRoute,
}

const NetWorthEntriesRouteWithChildren = NetWorthEntriesRoute._addFileChildren(
  NetWorthEntriesRouteChildren,
)

interface NetWorthRouteChildren {
  NetWorthCategoriesRoute: typeof NetWorthCategoriesRoute
  NetWorthEntriesRoute: typeof NetWorthEntriesRouteWithChildren
}

const NetWorthRouteChildren: NetWorthRouteChildren = {
  NetWorthCategoriesRoute: NetWorthCategoriesRoute,
  NetWorthEntriesRoute: NetWorthEntriesRouteWithChildren,
}

const NetWorthRouteWithChildren = NetWorthRoute._addFileChildren(
  NetWorthRouteChildren,
)

interface PlanningYearRouteChildren {
  PlanningYearAccountsRoute: typeof PlanningYearAccountsRoute
  PlanningYearBillsRoute: typeof PlanningYearBillsRoute
  PlanningYearEarningsRoute: typeof PlanningYearEarningsRoute
  PlanningYearPayslipsRoute: typeof PlanningYearPayslipsRoute
  PlanningYearTaxRatesRoute: typeof PlanningYearTaxRatesRoute
}

const PlanningYearRouteChildren: PlanningYearRouteChildren = {
  PlanningYearAccountsRoute: PlanningYearAccountsRoute,
  PlanningYearBillsRoute: PlanningYearBillsRoute,
  PlanningYearEarningsRoute: PlanningYearEarningsRoute,
  PlanningYearPayslipsRoute: PlanningYearPayslipsRoute,
  PlanningYearTaxRatesRoute: PlanningYearTaxRatesRoute,
}

const PlanningYearRouteWithChildren = PlanningYearRoute._addFileChildren(
  PlanningYearRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetWorthRoute: NetWorthRouteWithChildren,
  PlanningYearRoute: PlanningYearRouteWithChildren,
  PlanningIndexRoute: PlanningIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
