import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { buildSchema, isInterfaceType, isUnionType } from "graphql";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(here, "../src/__generated__/schema.graphql");
const outPath = resolve(here, "../src/__generated__/possible-types.ts");

const schema = buildSchema(readFileSync(schemaPath, "utf8"));
const typeMap = schema.getTypeMap();

const possibleTypes: Record<string, string[]> = {};
for (const name of Object.keys(typeMap).sort()) {
  if (name.startsWith("__")) continue;
  const type = typeMap[name];
  if (isInterfaceType(type) || isUnionType(type)) {
    possibleTypes[name] = schema
      .getPossibleTypes(type)
      .map((t) => t.name)
      .sort();
  }
}

writeFileSync(
  outPath,
  `// Generated by scripts/generate-possible-types.ts. Do not edit.\nexport const possibleTypes: Record<string, string[]> = ${JSON.stringify(
    possibleTypes,
    null,
    2,
  )};\n`,
);
